### ISSUE TITLE
NoSuchFieldError: No static field DRM_UNSUPPORTED

### ISSUE THREAD

**Issue by AdisAlagic** [vkay94/DoubleTapPlayerView#14]
ExoPlayer version: `r2.13.2`

```java
UncaughtExceptionHandler
    java.lang.NoSuchFieldError: No static field DRM_UNSUPPORTED of type Lcom/google/android/exoplayer2/drm/DrmSessionManager; in class Lcom/google/android/exoplayer2/drm/DrmSessionManager; or its superclasses (declaration of 'com.google.android.exoplayer2.drm.DrmSessionManager' appears in /data/app/com.*****==/base.apk)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManagerProvider.get(DefaultDrmSessionManagerProvider.java:82)
        at com.google.android.exoplayer2.source.hls.HlsMediaSource$Factory.createMediaSource(HlsMediaSource.java:395)
        at com.adisalagic.thedoctorsteam.ui.video.VideoActivity.hlsFromURI(VideoActivity.java:337)
        at com.adisalagic.thedoctorsteam.ui.video.VideoActivity.getSources(VideoActivity.java:299)
        at com.adisalagic.thedoctorsteam.ui.video.VideoActivity.start(VideoActivity.java:283)
        at com.adisalagic.thedoctorsteam.ui.video.VideoActivity.initPlayer(VideoActivity.java:274)
        at com.adisalagic.thedoctorsteam.ui.video.VideoActivity.onCreate(VideoActivity.java:201)
```

**Comment by vkay94** [comment]
There were some changes according DRM between 2.12.3 und the latest. Give me some minutes and I'll release a update with the latest version ;)

**Comment by vkay94** [comment]
It's live (1.0.2). Could you give feedback whether the issue was fixed? (I don't use DRM in the example app :))

**Comment by AdisAlagic** [comment]
Issue was fixed, thx
